version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # unless Gemfile is not in this location
    schedule:
      interval: "monthly"
    target-branch: "development" # if this branch exists
