language: ruby
rvm:
  - 2.6.3

before_install:
  - npm install

script:
  - ./script/build
  - npm test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=development
  - TRAVIS_CI=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
