dist: focal
language: ruby
rvm:
  - 3.1.2

before_install:
  - nvm install --lts # need to install a more recent version of node
  - npm install

script:
  - ./script/build
  - npm test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=development
  - TRAVIS_CI=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
