language: ruby
rvm:
  - 2.6.3

before_install:
  - npm install

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - TRAVIS_CI=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
