name: Test

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      JEKYLL_ENV: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.315.0
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 'lts/*'

      - name: Install additional packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install npm dependencies
        run: npm install

      - name: Run build script
        run: ./script/build

      - name: Run tests
        run: npm test
